// @flow
/*::
type Item = {
  id: number,
  itemname: number,
  itemtype: boolean,
  grademin: number,
  grademax: number,
  categoryid: string,
  aggregationcoef: number,
  itemtype: <manual|mod|category|course>,
  iteminstance: number // In the case than itemtype is category, iteminstace have the category parent id
};
*/
/*::
type AgregationEnum = {
    SIMPLE: 0,
    PONDERADO:10
}
 */
/*::
type Category = {
  id: number,
  fullname: string,
  depth: number,
  parent: number,
  grade_item: Item,
  aggregation: AgregationEnum
};
*/
/*::
type Column = {
    text: string
}
 */


/*::
type Student = {
  id: number,
  fistname: number,
  idnumber: string, // moodle user name, in other words, student code
  lastname: boolean,
  gradeIds: array
};
*/
/*::
type Agregation = {
  id: number,
  name: string
};
*/
/*::
type EditItemResponse = {
    category: Category,
    levels: Array
}
*/

/*::
type Grade = {
  id: number,
  userid: number,
  itemid: number,
  rawgrademin: number,
  rawgrademax: number,
  finalgrade: string,
};
*/
// Generate unique IDs for use as pseudo-private/protected names.
// Similar in concept to
// <http://wiki.ecmascript.org/doku.php?id=strawman:names>.
//
// The goals of this function are twofold:
//
// * Provide a way to generate a string guaranteed to be unique when compared
//   to other strings generated by this function.
// * Make the string complex enough that it is highly unlikely to be
//   accidentally duplicated by hand (this is key if you're using `ID`
//   as a private/protected name on an object).
//
// Use:
//
//     var privateName = ID();
//     var o = { 'public': 'foo' };
//     o[privateName] = 'bar';
var ID = function () {
    // Math.random should be unique because of its seeding algorithm.
    // Convert it to base 36 (numbers + letters), and grab the first 9 characters
    // after the decimal.
    return '_' + Math.random().toString(36).substr(2, 9);
};
define([
    'local_customgrader/vendor-vue',
    'local_customgrader/vendor-vue-router',
    'local_customgrader/vendor-vuex',
    'local_customgrader/vendor-vue-resource',
    'local_customgrader/vendor-vue-js-modal',
    'local_customgrader/vendor-vue-flex',
    'local_customgrader/vendor-vue-toasted',
    'local_customgrader/grader-store',
    'local_customgrader/grader-enums',
    'local_customgrader/grader-component-main',
    'local_customgrader/grader-router',
    'local_customgrader/grader-filters',
    ], function (
        Vue,
        VueRouter,
        Vuex,
        VueResource,
        VModal,
        VueFlex,
        VueToasted,
        g_store,
        g_enums,
        g_c_main,
        g_router,
        g_filters){
    Vue.use(VueRouter);
    Vue.use(Vuex);
    Vue.use(VueResource);
    Vue.use(VModal.default, { dialog: true });
    Vue.use(VueFlex);
    Vue.use(VueToasted.default);
    var graderVueEvents = {
      UPDATE_CATEGORY_OK: 'updateCategoryOK'
    };

    var modalsEnum = {
        EDIT_CATEGORY : 'edit-category',
        EDIT_ITEM : 'edit-item',
        ADD_ELEMENT: 'add-element'
    };

    const categoryElement = { name: 'CATEGORÍA' };
    const itemElement = { name: 'ÍTEM' };
    const partialElement = { name: 'PARCIAL' };
    const elementTypes = [categoryElement, itemElement, partialElement];

    var store = new Vuex.Store(g_store.store);

    var EditCategoryForm = Vue.component('EditCategoryForm', {
            // language=HTML
            template: `                
                    <form>
                        <h3>Editando Categoría: {{category.fullname}}</h3>
                            <label for="categoryFullName">
                                Nombre de la categoria
                            </label>
                            <input id="categoryFullName" v-model="categoryFullName">
                            <label for="aggregation">
                            Tipo de calificación
                            </label>
                            <select v-model="aggregation" id="aggregation">
                                <option 
                                        v-for="aggregation in aggregations"
                                        v-bind:value="aggregation.id">{{aggregation.name}}</option>
                            </select>
                            <button type="button" v-on:click="updateCategory">Guardar</button>
                    </form>
            `
        ,
        data: function() {
                return {
                    categoryFullName: '',
                    gradeTypeId: 0,
                    aggregation: g_enums.aggregations.PROMEDIO
                }
        },
        computed: {
            ...Vuex.mapState(['aggregations', 'selectedCategoryId']),
            ...Vuex.mapGetters({
                category: 'selectedCategory'
            }),
        },
        mounted: function () {
          this.categoryFullName = this.category.fullname;
          this.aggregation = this.category.aggregation;
        },
        methods: {
                updateCategory() {
                    this.$store.dispatch(
                        g_store.actions.UPDATE_CATEGORY,
                        {
                            ...this.category,
                                fullname: this.categoryFullName,
                                aggregation: this.aggregation,
                                aggregationcoef: 50

                        })
                        .then(()=> {
                            this.$emit(graderVueEvents.UPDATE_CATEGORY_OK);
                        })
                        .catch( ()=> {
                            this.$toasted.show('Ha habido un error guardando la categoria', {duration: 3000, theme:'bubble'});
                        });
                }
        }
        }
        );
    var CloseModalButton = Vue.component('CloseModalButton', {
        template: `
        <i class="fa fa-2x fa-times-circle" v-bind:style="closeButtonStyle"  @click="$modal.hide(modalName)"></i>
        `,
        props: {
            modalName: {
                type: String,
                required: true
            }
        },
        data: function() {
            return {
                closeButtonStyle: {
                    position: "absolute",
                    top: "10px",
                    right: "10px"
                }
            }
        }
    });
        var ModalAddElement = Vue.component('ModalAddElement', {
            template: `
       <modal 
        v-bind:name="modalName"
        v-bind:transition="'nice-modal-fade'"
        :draggable="true"
        >
            <AddElementForm></AddElementForm>
            <CloseModalButton v-bind:modalName="modalName"></CloseModalButton>
       </modal>
       `,
        data: function() {
                return {
                    modalName: modalsEnum.ADD_ELEMENT
                }
        }
        });
    var ModalEditCategory = Vue.component('ModalEditCategory',{
       template: `<modal
                    v-bind:name="modalName" 
                    v-bind:transition="'nice-modal-fade'"
                    :draggable="true"
                    >
                        <EditCategoryForm   v-on:updateCategoryOK="$modal.hide(modalName)"></EditCategoryForm>
                        <CloseModalButton v-bind:modalName="modalName"></CloseModalButton>
                   </modal>
       `,
        data: function () {
           return {
               modalName: modalsEnum.EDIT_CATEGORY
           }
        }
    });

    var AddElementForm = Vue.component('AddElementForm',{
       template: `
        
       <form>
       <h2>Añadir elemento</h2>
       <label></label>
       <select id="elementType">
           <option v-for="elementType in elementTypes" >
            {{elementType.name}}
           </option>
       </select>
       <label for="elementName">
        Nombre de el elemento
        </label>
        <input id="elementName">
        <template v-if="parentCategory.aggregation == weigthedMeanOfGrades">
            <label for="elementWeight">
            Peso
        </label>
        <input id="elementWeight">
        </template>
       <button type="button">Añadir</button>
       </form>
       `,
        data : function () {
           return {
               elementTypes: elementTypes
           }
        },
        computed: {
            ...Vuex.mapState(['selectedCategoryId']),
            ...Vuex.mapGetters(['selectedCategory']),
            parentCategory: function () {
                return this.selectedCategory;
            },
            weigthedMeanOfGrades: function () {
                return g_enums.aggregations.PROMEDIO;
            }
        }

    });


    var CategoryMiniMenuEdit = Vue.component('CategoryMiniMenuEdit', {
            template: `
                <div v-bind:style="style">
                    <i class="fa fa-edit" v-on:click="showEditDialog"></i>
                    <i class="fa fa-plus" v-on:click="showAddElementDialog"></i>
                    <i class="fa fa-trash"></i>
                </div>
            `,
        props: ['categoryId'],
        data: function () {
                return {
                    style: {
                        display: "grid",
                        gridTemplateColumns: "repeat(3, max-content)",
                        gridColumnGap: "8px"
                    }
                }
        },
        computed: {
                ...Vuex.mapGetters([
                    'categoryById'
                ]),
            category: function () {
                    return this.categoryById(this.categoryId);
                },
        },
        methods: {
            showEditDialog() {
                this.$store.commit(
                    g_store.mutations.SET_SELECTED_CATEGORY_ID,
                    this.category.id);
                this.$modal.show(modalsEnum.EDIT_CATEGORY);
            },
            showAddElementDialog() {
                this.$store.commit(
                    g_store.mutations.SET_SELECTED_CATEGORY_ID,
                    this.category.id);
                this.$modal.show(modalsEnum.ADD_ELEMENT);
            }
        }
        }
        );
    var ThCategory = Vue.component('ThCategory', {
       template : `    

                    <th 
                    @mouseover="showMenuItems = true"
                    @mouseout="showMenuItems = false" 
                    style="background-color: gray;" 
                    v-bind:colspan="childSize" 
                    class="category">
                        <flex-row align-v="center"  v-bind:style="editZoneStyles">
                           
                            <editable :content="category.fullname" @update="updateCategoryName"> </editable>
                            <p v-if="parentCategory.aggregation == weightedAggregation">{{category.grade_item.aggregationcoef | round(2)}}%</p>
                             <flex-col align-v="start"> 
                                <CategoryMiniMenuEdit v-bind:categoryId="category.id" v-show="showMenuItems"></CategoryMiniMenuEdit>
                             </flex-col> 
                        </flex-row>
                    </th>
       `,
        props: ['element'],
        data: function() {
           return {
               categoryName: '',
               editZoneStyles: {
                   display: 'grid',
                   gridTemplateColumns: 'repeat(2, max-content)',
                   gridColumnGap: '5px'
               },
               showMenuItems: false
           }
        },
        computed: {
            ...Vuex.mapGetters([
                'categoryById',
                'categoryChildSize'
            ]),
            category: function() {
                return this.categoryById(this.element.object.id);
            },
            childSize: function () {
                return this.categoryChildSize(this.category.id);
            },
            parentCategory: function() {
                return this.categoryById(this.category.parent);
            },
            weightedAggregation : function () {
                return g_enums.aggregations.PROMEDIO
            }

        },
        mounted: function (){
          this.categoryName = this.category.fullname;
        },
        methods: {
            updateCategoryName: function (categoryName) {
             this.$store.dispatch(
                 g_store.actions.UPDATE_CATEGORY,
                 {...this.category, fullname: categoryName})
           }
           }
    });

    var ItemActionsMini = Vue.component('ItemActionsMini', {
        template:`
        
        `,
        props: ['itemId']
    });

    var TrItems = Vue.component('TrItems', {
        template : `
                    <tr>
                    <th colspan="1" v-for="additionalColumnAtFirst in additionalColumnsAtFirst">{{additionalColumnAtFirst.text}}</th>
                    <template v-for="(item, index) in orderedItems">       
                        <ThItemCategory 
                        v-if="item.itemtype === 'category'" 
                        v-bind:itemId="item.id" 
                        v-bind:colspan="1"
                        ></ThItemCategory> 
                        
                        <ThItemManualAndMod 
                        v-if="item.itemtype === 'manual' || item.itemtype === 'mod'"  
                        v-bind:itemId="item.id" 
                        ></ThItemManualAndMod>
                     </template>
                     <th colspan="1" v-for="additionalColumnAtEnd in additionalColumnsAtEnd">{{additionalColumnAtEnd.text}}</th>
                     </tr>
   `,
        computed: {
            ...Vuex.mapGetters({
                orderedItems: 'orderedItemSet'
            }),
            ...Vuex.mapState([
                'additionalColumnsAtFirst',
                'additionalColumnsAtEnd'
            ])
        },
    });
        Vue.component('editable',{
            template:'<div contenteditable="true" @input="update">{{content}}</div>',
            props:['content'],
            methods:{
                update:function(event){
                    this.$emit('update',event.target.innerText);
                }
            }
        });

        var ThItemManualAndMod = Vue.component('ThItemManualAndMod', {
            template : `         
                <th v-cloak><!--v-on:click="deleteItem(item.id)"-->
                    <editable :content="item.itemname"  @update="saveNameChanges($event)"></editable>
                    <p v-if="parentCategory.aggregation == weightedAggregation">{{item.aggregationcoef | round(2)}}%</p>
                </th>
   `,
            props: ['itemId'],
            methods: {
                ...Vuex.mapActions({
                    deleteItem: g_store.actions.DELETE_ITEM
                }),
                activateEditName: function (){
                  this.editName = true;
                },
                saveNameChanges: function (itemName) {
                    if (itemName !== this.item.itemname) {
                        this.$store.dispatch(
                            g_store.actions.UPDATE_ITEM,
                            {...this.item, itemname: itemName}
                        );
                    }
                }
            },

            computed: {
                ...Vuex.mapState([
                    'items'
                ]),
                ...Vuex.mapGetters(['categoryById']),
                item: function () {
                    return this.items[this.itemId];
                },
                parentCategory: function () {
                    return this.categoryById(this.item.categoryid)
                },
                weightedAggregation: function (){
                    return g_enums.aggregations.PROMEDIO;
                }
            }
        });

        var ThItemCategory = Vue.component('ThItemCategory', {
            template : `         
                <th v-bind:colspan="colspan" >
                            {{itemName}}
                </th>
   `,
            props: ['itemId', 'colspan'],
            computed: {
                ...Vuex.mapState([
                    'items'
                ]),
                ...Vuex.mapGetters([
                    'categoryById'
                ]),
                item: function () {
                    return this.items[this.itemId];
                },
                categoryParent: function() {
                    return this.categoryById(this.item.iteminstance);
                },
                itemName: function() {
                    return 'TOTAL ' + this.categoryParent.fullname ;
                }
            },
        });

        var ThStudent = Vue.component('ThStudent',
            {
                // language=HTML
                template: `
                <th scope="row">
                    {{studentFullName}}
                </th>
                `,
                props: ['studentId'],
                computed: {
                    ...Vuex.mapGetters([
                        'studentById'

                    ]),
                    ...Vuex.mapGetters({
                        students: 'studentSet'
                    }),
                    student: function() {
                        return this.studentById(this.studentId);
                    },
                    studentFullName: function() {
                        return this.student.firstname + ' ' + this.student.lastname;
                    }
                }
            });
        var TdGrade = Vue.component('TdGrade',
            {
               template: `
                <td v-if="grade" > 
                <input type="number" v-bind:tabindex="tabIndex" step="0.1"  v-bind:max="grade.rawgrademax" v-bind:min="grade.rawgrademin" v-model="finalGrade">
                </td>
                `,
                props: ['gradeId', 'studentIndex', 'itemIndex'],
                methods: {
                    ...Vuex.mapActions({
                        updateGrade: g_store.actions.UPDATE_GRADE
                })
                },
                computed: {
                    ...Vuex.mapState([
                        'grades',
                        'course'
                    ]),
                    ...Vuex.mapGetters([
                        'studentsCount'
                    ]),
                    tabIndex: function() {
                        $('table_grader input');
                      return (this.itemIndex + 1) * this.studentsCount +  this.studentIndex + 1;
                    },
                    grade: function() {
                        return this.grades[this.gradeId];
                    },
                    finalGrade: {
                        get() {
                           return this.grade.finalgrade;
                        },
                        set(value) {
                            this.grade.finalgrade = value;
                            this.updateGrade(this.grade, this.course.id);
                        }
                    }
                }

            });
        var TrGrades = Vue.component('TrGrades',
            {
                template: `
                <tr>
                    
                    <ThStudent v-bind:studentId="student.id"></ThStudent>
                    <td >{{student.idnumber}}</td>
                    <TdGrade 
                    v-for="(gradeId, index) in student.gradeIds" 
                    :key="gradeId"
                    v-bind:studentIndex="studentIndex"
                    v-bind:itemIndex="index"
                    v-bind:gradeId="gradeId"
                    >
                    </TdGrade>
                   
                </tr>
                `,
                props: ['studentId', 'studentIndex'],
                computed: {
                    ...Vuex.mapState([
                       'students'
                    ]),
                    student: function() {
                      return this.students[this.studentId];
                    }
                }
            }
            );
        // language=HTML
        var Grader = Vue.component(g_c_main.name, g_c_main.component);


    var Home = Vue.component('home', {
        template: '<div>hola</div>',
        computed: {
            username() {
                // We will see what `params` is shortly
                return this.$route.params.username
            }
        },
        methods: {
            goBack () {
                window.history.length > 1
                    ? this.$router.go(-1)
                    : this.$router.push('/')
            }
        }
    });
    /** Filter registry */
    Vue.filter (g_filters.round.name, g_filters.round.func);

    var router = new VueRouter({
        routes: g_router.routes
    });
     var app = new Vue({
         store: store,
         router: router,
         components: {
             Grader,
             EditCategoryForm,
             Home,
             ThCategory,
             TrItems,
             ThItemManualAndMod
         }
     });


    return {
        init: function() {
            app.$mount('#app');
            $(document).ready(function() {

            });
        }
    };
}
);